export enum CommandEnum {
    ApplyTemplate = 'ApplyTemplateCommand',
    ApplyStreamBrief = 'ApplyStreamBriefCommand',
    EnhanceByAi = 'EnhanceByAiCommand',
    AddImages = 'AddImagesCommand',
    CreateNoteFromImages = 'CreateNoteFromImagesCommand',
    ApplyTemplateFromImage = 'ApplyTemplateFromImageCommand',
    GenerateHeaderMetadata = 'generate-header-metadata',
    RelocateNoteByLinkField = 'RelocateNoteByLinkFieldCommand',
    GenerateMissingNotesFromLinks = 'GenerateMissingNotesFromLinksCommand',
    CreateReciprocityLinksNotes = 'CreateReciprocityLinksNotesCommand',
    AnalyzeAndLinkEntities = 'AnalyzeAndLinkEntitiesCommand',
    GenerateMissingNotesFromListField = 'GenerateMissingNotesFromListFieldCommand',
    EnrichPlace = 'EnrichPlaceCommand',
    RelocatePlaceNote = 'RelocatePlaceNoteCommand',
    AddPlaceIdFromUrl = 'AddPlaceIdFromUrlCommand',
    SearchSpotifyTrack = 'SearchSpotifyTrack',
    ImportPlaylistTracks = 'ImportPlaylistTracks',
    SearchSpotifyArtist = 'SearchSpotifyArtistCommand',
    InsertLinkToSelectedPhoto = 'InsertLinkToSelectedPhotoCommand',
    OpenLinkedPhoto = 'OpenLinkedPhotoCommand',
}
