export const PlaceTypes = [
    "Lugares/Restaurantes",
    "Lugares/Monumentos",
    "Lugares/Paisajes",
    "Lugares/Playas",
    "Lugares/Montañas",
    "Lugares/Parques",
    "Lugares/Cafeterías",
    "Lugares/Bares",
    "Lugares/Museos-Artes",
    "Lugares/Museos-Ciencia",
    "Lugares/Hoteles",
    "Lugares/Tiendas",
    "Lugares/Estadios",
    "Lugares/Auditorios",
    "Lugares/Bibliotecas",
    "Lugares/Capitales",
    "Lugares/Municipios",
    "Lugares/Provincias",
    "Lugares/Regiones",
    "Lugares/Paises",
    "Lugares/Ciudades",
    "Lugares/Continentes",
    "Lugares/Barrios",
    "Lugares/Pueblos",
    "Lugares/Grandes-almacenes",
    "Lugares/Parques-naturales",
    "Lugares/Casas",
    "Lugares/Oficinas",
    "Lugares/Pisos",
    "Lugares/Calles"

] as const;

export type PlaceType = (typeof PlaceTypes)[number];
