export const TagFolderMappingRegistry: Record<string, string> = {
    "Personas/Conocidos-mios": "(Conocidos)",
    "Personas/Compañeros-de-trabajo": "(Conocidos)",
    "Personas/Vecinos": "(Conocidos)",
    "Personas/Familia": "(Familia)",
    "Personas/Públicas": "(Personajes)",
    "Personas/Históricas": "(Históricos)",
    "Obras/Películas": "(Audiovisuales)",
    "Obras/Videojuegos": "(Audiovisuales)",
    "Obras/Libros": "(Libros)",
    "Obras/Bebidas": "(Gastronomía)",
    "Obras/Comidas": "(Gastronomía)",
    "Obras/Canales-Stream": "(Medios)",
    "Obras/Series-TV": "(Audiovisuales)",
    "Orgs/Multinacionales": "(Empresas)",
    "Orgs/Empresas": "(Empresas)",
    "Orgs/Colegios": "(Colegios)",
    "Lugares/Restaurantes": "(Restaurantes)",
    "Lugares/Bares": "(Bares)",
    "Lugares/Negocios": "(Negocios)",
    "Lugares/Fiestas": "(Eventos)",
};
