export const TagFolderMappingRegistry: Record<string, string> = {
    "Personas/Conocidos-mios": "(Personas-Conocidas)",
    "Personas/Compañeros-de-trabajo": "(Personas-Conocidas)",
    "Personas/Vecinos": "(Personas-Conocidas)",
    "Personas/Familia": "(Personas-Familia)",
    "Personas/Públicas": "(Personajes)",
    "Personas/Historicas": "(Personajes-Historicos)",
    "Obras/Películas": "(Obras-Audiovisual)",
    "Obras/Videojuegos": "(Obras-Audiovisual)",
    "Obras/Libros": "(Obras-Libros)",
    "Obras/Bebidas": "(Gastronomía)",
    "Obras/Comidas": "(Gastronomía)",
    "Obras/Canales-Stream": "(Medios)",
    "Obras/Series-TV": "(Obras-Audiovisual)",
    "Orgs/Multinacionales": "(Empresas)",
    "Orgs/Empresas": "(Empresas)",
};
