export declare const FrontmatterKeys: {
    readonly EloCommands: "!!commands";
    readonly EloPrompt: "!!prompt";
    readonly EloPromptUrl: "!!promptUrl";
    readonly EloImages: "!!images";
    readonly EloAppleContactId: "!!appleContactId";
    readonly Municipio: "Municipio";
    readonly Provincia: "Provincia";
    readonly LugarId: "Lugar Id";
    readonly Region: "Región";
    readonly Pais: "País";
    readonly Paises: "Países";
    readonly Lugares: "Lugares";
    readonly Lugar: "Lugar";
    readonly SedePrincipal: "Sede principal";
    readonly Latitud: "Latitud";
    readonly Longitud: "Longitud";
    readonly Url: "Url";
    readonly SpotifyUri: "Spotify uri";
    readonly Capital: "Capital";
    readonly Tags: "tags";
    readonly Conocidos: "Conocidos";
    readonly Hijos: "Hijos";
    readonly Padres: "Padres";
    readonly Pareja: "Pareja";
    readonly Exparejas: "Exparejas";
    readonly Hermanos: "Hermanos";
    readonly Familiares: "Familiares";
    readonly CompanerosTrabajo: "Compañeros de trabajo";
    readonly Jefes: "Jefes";
    readonly Empleados: "Empleados";
    readonly EstilosMusicales: "Estilos musicales";
    readonly SpotifyPopularity: "Spotify popularidad";
    readonly Telefono: "Teléfono";
    readonly Email: "Email";
    readonly Cumpleanos: "Cumpleaños";
    readonly Apodo: "Apodo";
    readonly Puesto: "Puesto de trabajo";
    readonly Empresa: "Empresa";
    readonly Direcciones: "Direcciones";
    readonly Urls: "Urls";
    readonly Eventos: "Eventos";
    readonly Relaciones: "Relaciones";
    readonly Genero: "Género";
    readonly Ocupaciones: "Ocupaciones";
    readonly Intereses: "Intereses";
    readonly Habilidades: "Habilidades";
    readonly Residencias: "Residencias";
};
export type FrontmatterKey = (typeof FrontmatterKeys)[keyof typeof FrontmatterKeys];
export interface FrontmatterFieldConfig {
    key: FrontmatterKey;
    description: string;
    type: 'string' | 'number' | 'boolean' | 'date' | 'array';
    asLink?: boolean;
    reciprocityField?: FrontmatterKey;
    amongField?: FrontmatterKey;
    isRelocateField?: boolean;
    commands?: string[];
}
export declare const FrontmatterRegistry: Record<string, FrontmatterFieldConfig>;
